openapi: 3.0.2
info:
  title: Case Management API
  description: API for managing cases with emails
  version: 1.0.0
servers:
  - url: http://localhost:5000
paths:
  /case/{case_id}:
    get:
      summary: Retrieve a case by ID
      parameters:
        - name: case_id
          in: path
          description: ID of the case to retrieve
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  case_id:
                    type: integer
                  email:
                    type: string
        '404':
          description: Case ID not found
    post:
      summary: Create a new case
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
      responses:
        '201':
          description: Case created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  case_id:
                    type: integer
                  email:
                    type: string
        '400':
          description: Bad request - missing email
        '409':
          description: Case ID already exists
    put:
      summary: Update an existing case
      parameters:
        - name: case_id
          in: path
          description: ID of the case to update
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
      responses:
        '200':
          description: Case updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  case_id:
                    type: integer
                  email:
                    type: string
        '400':
          description: Bad request - missing email
        '404':
          description: Case ID not found
    delete:
      summary: Delete a case by ID
      parameters:
        - name: case_id
          in: path
          description: ID of the case to delete
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Case deleted successfully
        '404':
          description: Case ID not found
